### PR TITLE
Fixes from PR code review

### PR DESCRIPTION
**Pull request by BryanCutler**
Addressed some feedback from the PR.  I'll merge these changes unless there are comments, cc @wesm @icexelloss
* renamed to ArrowConverters
* encapsulated Arrow usage in ArrowConverters
* defined ArrowPayload as Iterator of ArrowRecordBatches
* minor cleanup

### CODE REVIEW

**Comment by icexelloss** [comment]
LGTM

**Review by wesm — APPROVED** [review]
LGTM also, thank you

**Comment by wesm** [comment]
@BryanCutler there are some API changes in pyarrow, I'm writing a patch now to fix

**Comment by BryanCutler** [comment]
Ok thanks, I'll make sure to get that updated in the PR also

**Comment by wesm** [comment]
Just waiting on Spark to compile to check that things still work =S

**Pull request closed without merging**
