### PR TITLE
Add support for date/timestamp/binary; Add more numbers to benchmark.…

### PR DESCRIPTION
**Pull request by icexelloss**
…py; Fix memory leaking bug

## What changes were proposed in this pull request?
1. Support for date/timestamp/binary type
2. benchmark of internalRowsToArrowRecordBatch
3. Fix memory leaking bug in Arrow.scala

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)
(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

Please review http://spark.apache.org/contributing.html before opening a pull request.

### CODE REVIEW

**Comment by BryanCutler** [comment]
LGTM, I had made a few changes.  I can resolve the conflicts when I merge unless you have already started?

**Comment by icexelloss** [comment]
Bryan, I will do it

**Comment by BryanCutler** [comment]
No worries, I already did.  I'm just about to update the JIRA, so wanted to get this in asap

**Comment by icexelloss** [comment]
Cool, thx!

**Pull request closed without merging**
