### PR TITLE
Account for pyarrow API changes, read multiple record batches

### PR DESCRIPTION
**Pull request by wesm**
Sorry about the API break. I don't expect it to happen too many more times

### CODE REVIEW

**Comment by wesm** [comment]
FWIW, on my laptop, starting with the benchmark.py script from the JIRA issue, I have:

```
%%prun -s cumulative 

frames = [df.toPandas(useArrow=True) for i in range(10)]

         19379 function calls (19279 primitive calls) in 3.651 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    3.651    3.651 {built-in method builtins.exec}
        1    0.000    0.000    3.651    3.651 <string>:3(<module>)
        1    0.000    0.000    3.651    3.651 <string>:3(<listcomp>)
       10    0.000    0.000    3.651    0.365 dataframe.py:1570(toPandas)
       10    0.001    0.000    3.603    0.360 dataframe.py:394(collectAsArrow)
     1041    0.002    0.000    3.576    0.003 socket.py:562(readinto)
     1041    3.571    0.003    3.571    0.003 {method 'recv_into' of '_socket.socket' objects}
       30    0.000    0.000    3.553    0.118 java_gateway.py:1123(__call__)
       30    0.000    0.000    3.549    0.118 java_gateway.py:860(send_command)
       30    0.001    0.000    3.549    0.118 java_gateway.py:1006(send_command)
       30    0.001    0.000    3.546    0.118 {method 'readline' of '_io.BufferedReader' objects}
       10    0.035    0.003    0.048    0.005 {method 'to_pandas' of 'pyarrow.table.Table' objects}
       20    0.000    0.000    0.038    0.002 rdd.py:121(_load_from_socket)
       20    0.000    0.000    0.035    0.002 serializers.py:141(load_stream)
       20    0.000    0.000    0.035    0.002 serializers.py:160(_read_with_length)
       30    0.002    0.000    0.033    0.001 {method 'read' of '_io.BufferedReader' objects}
       10    0.000    0.000    0.010    0.001 traceback_utils.py:61(__init__)
       10    0.001    0.000    0.010    0.001 traceback_utils.py:26(first_spark_call)
       10    0.000    0.000    0.008    0.001 traceback.py:196(extract_stack)
       10    0.002    0.000    0.008    0.001 traceback.py:313(extract)
    50/30    0.000    0.000    0.007    0.000 <frozen importlib._bootstrap>:966(_find_and_load)
       10    0.000    0.000    0.006    0.001 traceback_utils.py:70(__enter__)
    50/30    0.000    0.000    0.006    0.000 <frozen importlib._bootstrap>:939(_find_and_load_unlocked)
```

So about 98% of the runtime is obtaining the data payload from Spark, only 2% Arrow deserialization

**Comment by BryanCutler** [comment]
No problem, looks much better now with `read_all()`, and I see that's multi-threaded now, cool!

That's an interesting profile, hopefully collecting at the executors will put a dent in that.

**Comment by wesm** [comment]
@BryanCutler @icexelloss can you kindly give me instructions how to see the Spark driver / executor logs? I added some logging statements and I've been scouring the internet trying to see how to get these to print to the console or a file but I haven't had any success. The codebase is littered with log4j properties files, but I can't tell which one I need to edit. 

This is based on starting Spark in a Jupyter notebook using effectively the code found in the benchmark.py in https://issues.apache.org/jira/browse/SPARK-13534

**Comment by icexelloss** [comment]
Wes,

The one that spark uses should be conf/log4j.properties, have you tried
that one?

**Comment by wesm** [comment]
Can you give me an example properties file and let me know where to find the logs? Do I need to rebuild from scratch?

**Comment by wesm** [comment]
@BryanCutler I put up a branch here https://github.com/wesm/spark/commit/de4c6edb6f1572a11fac78b2e1527fb3444e499f -- trying desperately to get logging output from Spark SQL but not having any success

**Comment by BryanCutler** [comment]
@wesm, there should be a sample log4j .template file in the SPARK_HOME/conf
dir.  I'll take a look at the branch as soon as I get in.

**Comment by BryanCutler** [comment]
Your changes worked for me, from running on the command line in local mode, at least.  I'm not sure if the driver log would get redirected somewhere when running Jupyter though.  I ran with this command (just redirecting stderr, since the logs go there by default)
```
$ bin/spark-submit benchmark.py 2>&1 | grep -i "arrow\|Time to collect"
internal rows to arrow record batch
toPandas with arrow
Time to collect: 35812308
17/01/31 10:19:50 INFO ArrowConverters: Arrow conversion time: 672001
Time to collect: 27389484
17/01/31 10:19:51 INFO ArrowConverters: Arrow conversion time: 530875
Time to collect: 51617540
17/01/31 10:19:51 INFO ArrowConverters: Arrow conversion time: 602984
Time to collect: 30297656
17/01/31 10:19:51 INFO ArrowConverters: Arrow conversion time: 792255
Time to collect: 29415422
17/01/31 10:19:51 INFO ArrowConverters: Arrow conversion time: 745879
...
```

**Comment by BryanCutler** [comment]
[log4j.properties.txt](https://github.com/BryanCutler/spark/files/742802/log4j.properties.txt)
Here is my log4j file, just remove .txt extension and put in `SPARK_HOME/conf`

**Comment by wesm** [comment]
Will give it a shot. Am using Parquet for the benchmarks which appears to cause some problems with the logging system

**Comment by wesm** [comment]
I'm able to get the logs in spark-submit, trying to get them interactively in a Jupyter notebook or via `bin/pyspark` gives me nothing. If you know how to get that to work, it would be a huge help

**Comment by BryanCutler** [comment]
I add this section to log4j file to setup an appender for the `ArrowConverter` class
```
log4j.logger.org.apache.spark.sql.ArrowConverters=INFO, arrow
log4j.additivity.org.apache.spark.sql.ArrowConverters=false
log4j.appender.arrow=org.apache.log4j.ConsoleAppender
log4j.appender.arrow.target=System.err
log4j.appender.arrow.layout=org.apache.log4j.PatternLayout
log4j.appender.arrow.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
```
Then running the code below in pyspark shows your log
```python
In [3]: df = spark.createDataFrame([(1, "1"), (2, "2"), (1, "2"), (1, "2")], ["key", "value"])

In [4]: df.toPandas(useArrow=True)
Time to collect: 766972422                                                      
17/01/31 11:38:54 INFO ArrowConverters: Arrow conversion time: 48550299
```
I don't have a Jupyter install at the moment, but I think it would apply there too.  You can also set `sc.setLogLevel("INFO")` which should enable everything.  Hope that helps!

**Comment by wesm** [comment]
thanks, I will try when I can!

**Pull request closed without merging**
